spring.config.import=optional:dotenv:.env
spring.application.name=budgetpilot

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWKS_URL}

anthropic.api.key=${ANTHROPIC_API_KEY:}
anthropic.model=claude-haiku-4-5